server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3366/dreamtour
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#自己的配置信息
myProperties:
  pageSize: 2 #分页大小